### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by ALI97852** [Stardust-Labs-MC/Amplified-Nether#10]
### Describe your enhancement/improvement, with context and reasoning.

HELLO THERE

**Comment by ALI97852** [comment]
HIIO ALEX NSTM V KHOSG SGDM

**Comment by ALI97852** [comment]
خیلی خوب واقعا ممنون ممنونم ازتون

**Comment by catter1** [comment]
Please stop, this issue tracker is for issues regarding our projects only.
