### ISSUE TITLE
[Bug] [1.18.2] Crashes with Bygone Nether

### ISSUE THREAD

**Issue by DoctorMage** [Stardust-Labs-MC/Amplified-Nether#4]
### What Minecraft version(s) does this apply to?

1.18.2

### Project version

Amplified_Nether_v1.1.1.jar

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Example seed -2709617820162703822
/tp -10752 -51  -26112 Nether Coordsa

Going beyond vanilla nether build limit in basalt biomes will cause the game to crash

### Additional context

Mods Involved

Amplified Nether

Debug Log
https://gist.github.com/DoctorMage/c63624d6f08d145d3dd202f2707416d0

I have tested the same seed and coordinates in 1.19.2 and it seems fine

Unsure which mod to report this to so reported to both

**Comment by catter1** [comment]
This is very unlikely to be caused by Amplified Nether, as it's *essentially* just the normal nether with mountains and a higher height limit. But we'll see what [Bygone Nether](https://github.com/izofar/bygone-nether/issues/29) says.

**Comment by izofar** [comment]
I have confirmed this is my bug. You can close on your end.
