### ISSUE TITLE
[Bug] Memory Leak

### ISSUE THREAD

**Issue by isdi0** [Stardust-Labs-MC/Amplified-Nether#5]
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

v1.2.1

### Mod or datapack version?

Mod (Forge)

### Describe the bug

When exploring the nether, memory usage will continuously increase to the point of stuttering and eventual crashing.

### Additional context

Specific game version is 1.19.2, and I am using GraalVM Java 17, along with Bobby at 48 chunks render distance

**Comment by catter1** [comment]
Does the error also occur without Amplified Nether? With the same Forge/mod setup.
