### ISSUE TITLE
[Enhancement] Nether Roof Biome

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Stardust-Labs-MC/Amplified-Nether#7]
Currently, the biome above the nether roof in the amplified version of the nether is `minecraft:plains` but that means when you increase the build height (which is something I feel a lot of people might do due to the nether roof being the best location for travel, it makes everything above plains and thus mobs spawn. Overworld mobs spawn, everywhere, no matter the light level.

**Comment by catter1** [comment]
Are you adding the build height raiser *after* the nether is generated for the first time (i.e. in existing chunks), or before the nether is generated (i.e. adding on a brand new world)?

**Comment by Kazuhiko-Gushiken** [comment]
Oh, I added it after. I actually noticed only some biomes don't stretch up into infinity. One such being the soul sand valley, as others like the crimson forest and warped forest biomes extend up and up.

**Comment by catter1** [comment]
If you add it to an existing nether, this behavior will happen. If the height is extended on a chunk that was already generated, the game will call that extended space `minecraft:plains`. This is because the game doesn't have a way to generate biomes for height that doesn't exist.
