### ISSUE TITLE
[Enhancement] PaperMC support

### ISSUE THREAD

**Issue by athyfr** [Stardust-Labs-MC/Amplified-Nether#8]
### Describe your enhancement/improvement, with context and reasoning.

This mod should be ported to PaperMC.

I would love to be able to use this mod in my personal server, but it uses PaperMC (with plugins exclusive to PaperMC), so I can't use it.

**Comment by catter1** [comment]
No need. We already have a datapack version of Amplified Nether, and datapacks work on PaperMC. Download it here: https://www.stardustlabs.net/version-library

**Comment by athyfr** [comment]
Wonderful! Thanks for the info!
