### ISSUE TITLE
[Bug] Alex's caves can generate in the nether

### ISSUE THREAD

**Issue by Lunaticol** [Stardust-Labs-MC/Amplified-Nether#9]
### What Minecraft version(s) does this apply to?

1.20 - 1.20.1

### Project version

1.2.5

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

It seems because Amplified nether uses cave generation to extend the nether height (I'm assuming it does this as the nether seems to exhibit some cave generation behaviors) it can cause mods such as Alex's Caves to generate within the nether.

**Comment by catter1** [comment]
This is not somethng that we would cause, nor can do about on our end. This should be reported to Alex's Caves instead.
